# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_CORESIGHT_CSR) += coresight-csr.o

obj-$(CONFIG_CORESIGHT_CTI) += coresight-cti.o
coresight-cti-objs += coresight-cti-core.o coresight-cti-platform.o coresight-cti-sysfs.o

obj-$(CONFIG_CORESIGHT_DUMMY) += coresight-dummy.o

obj-$(CONFIG_CORESIGHT_SOURCE_ETM4X) += coresight-etm4x.o
coresight-etm4x-objs += coresight-etm4x-cfg.o coresight-etm4x-core.o coresight-etm4x-sysfs.o

obj-$(CONFIG_CORESIGHT_LINKS_AND_SINKS) += coresight-funnel.o

obj-$(CONFIG_CORESIGHT) += coresight.o
coresight-objs += coresight-cfg-afdo.o coresight-cfg-preload.o coresight-config.o coresight-core.o coresight-etm-perf.o coresight-platform.o coresight-syscfg-configfs.o coresight-syscfg.o coresight-sysfs.o coresight-trace-id.o

obj-$(CONFIG_CORESIGHT_QMI) += coresight-qmi.o

obj-$(CONFIG_CORESIGHT_REMOTE_ETM) += coresight-remote-etm.o

obj-$(CONFIG_CORESIGHT_LINKS_AND_SINKS) += coresight-replicator.o

obj-$(CONFIG_CORESIGHT_STM) += coresight-stm.o

obj-$(CONFIG_CORESIGHT_TGU) += coresight-tgu.o

obj-$(CONFIG_CORESIGHT_LINK_AND_SINK_TMC) += coresight-tmc.o
coresight-tmc-objs += coresight-byte-cntr.o coresight-tmc-core.o coresight-tmc-etf.o coresight-tmc-etr.o coresight-tmc-usb.o

obj-$(CONFIG_CORESIGHT_REMOTE_ETM) += coresight-tmc-sec.o

obj-$(CONFIG_CORESIGHT_TPDA) += coresight-tpda.o

obj-$(CONFIG_CORESIGHT_TPDM) += coresight-tpdm.o

obj-$(CONFIG_CORESIGHT_TRACE_NOC) += coresight-trace-noc.o

obj-$(CONFIG_CORESIGHT_UETM) += coresight-uetm.o


# --- marble: objs upstream restaurados ---
subdir-ccflags-y += -Wextra -Wunused -Wno-unused-parameter
subdir-ccflags-y += -Wmissing-declarations
subdir-ccflags-y += -Wmissing-format-attribute
subdir-ccflags-y += -Wmissing-prototypes
subdir-ccflags-y += -Wold-style-definition
subdir-ccflags-y += -Wmissing-include-dirs
subdir-ccflags-y += -Wno-sign-compare
condflags := \
	$(call cc-option, -Wrestrict)				\
	$(call cc-option, -Wunused-but-set-variable)		\
	$(call cc-option, -Wunused-const-variable)		\
	$(call cc-option, -Wpacked-not-aligned)			\
	$(call cc-option, -Wformat-overflow)			\
	$(call cc-option, -Wformat-truncation)			\
	$(call cc-option, -Wstringop-overflow)			\
	$(call cc-option, -Wstringop-truncation)
subdir-ccflags-y += $(condflags)
coresight-y := coresight-core.o  coresight-etm-perf.o coresight-platform.o \
		coresight-sysfs.o coresight-syscfg.o coresight-config.o \
		coresight-cfg-preload.o coresight-cfg-afdo.o \
		coresight-syscfg-configfs.o coresight-trace-id.o
coresight-tmc-y := coresight-tmc-core.o coresight-tmc-etf.o \
		      coresight-tmc-etr.o
obj-$(CONFIG_CORESIGHT_SINK_TPIU) += coresight-tpiu.o
obj-$(CONFIG_CORESIGHT_SINK_ETBV10) += coresight-etb10.o
obj-$(CONFIG_CORESIGHT_SOURCE_ETM3X) += coresight-etm3x.o
coresight-etm3x-y := coresight-etm3x-core.o coresight-etm-cp14.o \
		     coresight-etm3x-sysfs.o
coresight-etm4x-y := coresight-etm4x-core.o coresight-etm4x-sysfs.o \
			coresight-etm4x-cfg.o
obj-$(CONFIG_CORESIGHT_CPU_DEBUG) += coresight-cpu-debug.o
obj-$(CONFIG_CORESIGHT_CATU) += coresight-catu.o
obj-$(CONFIG_CORESIGHT_TRBE) += coresight-trbe.o
coresight-cti-y := coresight-cti-core.o	coresight-cti-platform.o \
		   coresight-cti-sysfs.o
obj-$(CONFIG_ULTRASOC_SMB) += ultrasoc-smb.o
