# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_PHY_NXP_PTN3222) += phy-nxp-ptn3222.o


# --- marble: objs upstream restaurados ---
obj-$(CONFIG_GENERIC_PHY) += phy-core.o
obj-$(CONFIG_GENERIC_PHY_MIPI_DPHY) += phy-core-mipi-dphy.o
obj-$(CONFIG_PHY_CAN_TRANSCEIVER) += phy-can-transceiver.o
obj-$(CONFIG_PHY_LPC18XX_USB_OTG) += phy-lpc18xx-usb-otg.o
obj-$(CONFIG_PHY_XGENE) += phy-xgene.o
obj-$(CONFIG_PHY_PISTACHIO_USB) += phy-pistachio-usb.o
obj-$(CONFIG_USB_LGM_PHY) += phy-lgm-usb.o
obj-$(CONFIG_PHY_AIROHA_PCIE) += phy-airoha-pcie.o
obj-y += starfive/ cadence/ marvell/ broadcom/ st/ motorola/ freescale/ hisilicon/ intel/ amlogic/ qualcomm/ microchip/ ingenic/ ralink/ xilinx/ ti/ mscc/ lantiq/ renesas/ socionext/ mediatek/ tegra/ rockchip/ allwinner/ sunplus/ samsung/ nuvoton/ realtek/
