build.config.msm.autogvm
build.config.msm.sun
build.config.msm.sun.allyes
build.config.msm.canoe
build.config.msm.alor.le
build.config.msm.bengal
build.config.msm.lahaina
build.config.msm.monaco
build.config.msm.seraph
build.config.msm.seraph.vm
build.config.msm.vienna
build.config.msm.vienna.le
build.config.msm.gen3auto
build.config.msm.hamoa
build.config.msm.malabar
build.config.msm.shikra
build.config.msm.shikra_tiny
build.config.msm.shikra_auto
build.config.msm.hamoa_la
build.config.msm.glymur
build.config.msm.waipio
