/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DPD_PROXY_INTERNAL_H
#define _DPD_PROXY_INTERNAL_H

/*
 * Service Interface Definitions - ISecureMemoryManager
 * ----------------------------------------------------
 */
#define CSecureMemoryManager_UID (448)

/*
 * MapMemory service call:
 * Input buffer: struct imm_map_cmd[]
 * Input object: memory object
 */
#define IMM_SVC_MAP (0)
#define IMM_F_READ BIT(0)
#define IMM_F_WRITE BIT(1)
#define IMM_F_EXEC BIT(2)
#define IMM_VALID_FLAGS GENMASK(2, 0)

struct imm_map_cmd {
	u32 eVM;
	u32 flags;
	u64 iova;
	u64 size;
	u64 offset;
} __packed;

/*
 * UnmapMemory service call:
 * Input buffer: struct imm_unmap_cmd
 * Input object: memory object
 *
 * Note: In the TEE service, this structure is defined inline
 * in an autogenerated function 'IMemoryManager_DEFINE_INVOKE'.
 */
#define IMM_SVC_UNMAP (1)

struct imm_unmap_cmd {
	u64 iova;
	u64 size;
	u32 eVM;
} __packed;

/*
 * Registers a smcinvoke object for handling iommu fault notifications
 * The object methods:
 *
 * notifyFault informs HLOS that a fault has occurred. This notification is sent
 * after the TEE handles the fault via the smmuv2 "Terminate" model.
 * @args[0] - SI_AT_IB with type 'struct imm_fault_info'
 * @args[1] - SI_AT_END
 * notifyFault(struct si_object *object, struct si_arg args[])
 *
 *
 * The following arguments are expected to IMM_SVC_REGISTER_CBO
 * @args[0] - SI_AT_IO described above
 * @args[1] - SI_AT_END
 * The TEE equivalent API is "CSecureMemoryManager_registerSMMUFaultHandler"
 */
#define IMM_SVC_REGISTER_CBO (2)
#define IMM_CBO_METHOD_NOTIFY_FAULT (0)

/*
 * base_address - The physical address of the iommu hardware instance.
 * cbidx - Hardware context bank index
 * eVM -  id passed in map and unmap commands.
 * other fields are standard arm-smmu-v2 registers.
 * TEE-equivalent: 'struct ISMMUNotificationHandler_SmmuFaultContext'.
 */
struct imm_fault_info {
	u32 base_address;
	u32 cbidx;
	u32 scr0;
	u32 nscr0;
	u32 sctlr;
	u32 tcr;
	u32 fsr;
	u32 fsr_restore;
	u32 cbar;
	u32 cba2r;
	u64 far;
	u64 ipafar;
	u64 ttbr0;
	u64 ttbr1;
	u32 fsynr0;
	u32 fsynr1;
	u32 cbfrsynra;
	u32 eVM;
	u64 reserved0;
	u64 reserved1;
	u64 reserved2;
	u64 reserved3;
	u64 reserved4;
} __packed;

#endif /* _DPD_PROXY_INTERNAL_H */
