# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_GH_ARM64_DRV) += gh_arm_drv.o
gh_arm_drv-objs += gh_arm.o irq.o reset.o


# --- marble: objs upstream restaurados ---
obj-$(CONFIG_GUNYAH_HYPERCALLS) += gunyah_hypercall.o
