# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_QCOM_POWER_TELEMETRY_FRAMEWORK) += qptf.o

obj-$(CONFIG_QCOM_POWER_TELEMETRY_HW) += qti_power_telemetry.o

obj-$(CONFIG_QCOM_POWER_TELEMETRY_DATA_SHARE) += qti_ptd_share.o

obj-$(CONFIG_QCOM_QPT_RPMSG_POWERCAP) += qpt_rpmsg_powercap.o

