# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_SPMI_MSM_PMIC_ARB_DEBUG) += spmi-pmic-arb-debug.o

obj-$(CONFIG_SPMI_MSM_PMIC_ARB) += spmi-pmic-arb.o

obj-$(CONFIG_VIOSPMI_MSM_PMIC_ARB) += viospmi-pmic-arb.o


# --- marble: objs upstream restaurados ---
obj-$(CONFIG_SPMI) += spmi-devres.o spmi.o
obj-$(CONFIG_SPMI_HISI3670) += hisi-spmi-controller.o
obj-$(CONFIG_SPMI_MTK_PMIF) += spmi-mtk-pmif.o
