// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#include <linux/firmware/qcom/qcom_scm.h>
#include <linux/qtee_shmbridge.h>
#include <linux/interrupt.h>
#include <linux/of_irq.h>
#include <linux/firmware/qcom/si_core_xts.h>

#include "si_core.h"

#define SI_OBJECT_OP_CALLRUNNABLE 0
#define SI_DOORBELL_UID	439
#define SI_REGISTER_TASK_RUNNER_UID 437

/* Number of bytes allocated for doorbell memory object. */
#define DOORBELL_MO_SIZE 0x1000
/* Number of concurrent doorbell running in QTEE. */
#define DOORBELL_CONCURRENT_RUNNER_NR 8

struct doorbell;

/**
 * struct doorbell_msg - Doorbell message format.
 * @tag: current doorbell message identifier.
 * @len: length of data in @buff.
 * @buff: current doorbell request payload.
 */
struct doorbell_msg {
	u32 tag;
	u32 len;
	u8 buff[];
};

/**
 * struct doorbell_mo_info - Shared memory object for the doorbell messages.
 * @object: si_object representing the memory object as seen by QTEE.
 * @vaddr: virtual address for the shared buffer.
 * @size: size in bytes of the shared buffer.
 * @paddr: physical address for the shared buffer.
 */
struct doorbell_mo_info {
	struct si_object *object;
	void *vaddr;
	size_t size;
	phys_addr_t paddr;
};

/**
 * struct runner_worker - Per-doorbell worker used to process callbacks.
 * @work: work item queued from the IRQ handler onto @doorbell->wq.
 * @doorbell: back pointer to the owning doorbell instance.
 * @oic: si-core invoke context used to dispatch the callback request. The output
 *       message buffer (@oic.out.msg.addr) is used as per-worker storage for a
 *       private copy of the doorbell payload; it is allocated in worker_oic_init()
 *       and freed when the worker is returned to the idle pool.
 * @node: node linking this worker into @doorbell->idle_workers or
 *        @doorbell->busy_workers.
 */
struct runner_worker {
	struct work_struct work;
	struct doorbell *doorbell;
	struct si_object_invoke_ctx oic;
	struct list_head node;
};

/**
 * struct doorbell - Main doorbell state.
 * @mo_info: shared memory object used to receive doorbell messages.
 * @service: QTEE doorbell service object.
 * @task_runner: QTEE task-runner service object.
 * @lock: protects worker lists and @pending.
 * @cbo: callback object exported to QTEE for task runner.
 * @idle_workers: workers currently idle and available for new doorbells.
 * @busy_workers: workers currently processing a doorbell.
 * @pending: set when at least one doorbell arrived while all workers were busy.
 * @wq: workqueue used to run doorbell callbacks in process context.
 * @irq: irq generated by QTEE.
 */
struct doorbell {
	struct doorbell_mo_info mo_info;

	struct si_object *service;
	struct si_object *task_runner;
	/* Synchronize access to @idle_workers, @busy_workers, and @pending. */
	spinlock_t lock;
	struct si_object cbo;
	struct list_head idle_workers;
	struct list_head busy_workers;
	bool pending;

	struct workqueue_struct *wq;
	struct runner_worker workers[DOORBELL_CONCURRENT_RUNNER_NR];

	int irq;
};

/**
 * doorbell_worker_alloc() - Reserve an idle runner worker for doorbell work.
 * @doorbell: doorbell instance that owns the worker pool.
 *
 * If an idle worker is available, move it from @doorbell->idle_workers to
 * @doorbell->busy_workers to reserve it for use by the caller.
 *
 * Context: Must be called with @doorbell->lock held.
 * Return: Pointer to a reserved worker on success, or %NULL if no idle worker
 * is available.
 */
static struct runner_worker *doorbell_worker_alloc(struct doorbell *doorbell)
{
	struct runner_worker *worker;

	if (list_empty(&doorbell->idle_workers))
		return NULL;

	worker = list_first_entry(&doorbell->idle_workers,
				  struct runner_worker, node);
	/* Reserve a worker by moving it to busy_workers. */
	list_move(&worker->node, &doorbell->busy_workers);

	return worker;
}

/* Context: Must be called with @worker->doorbell->lock held. */
static void doorbell_worker_free(struct runner_worker *worker)
{
	kfree(worker->oic.out.msg.addr);
	/* Invalidate the oic. */
	worker->oic.out.msg.addr = NULL;
	/* Release @worker by moving it to idle_workers. */
	list_move(&worker->node, &worker->doorbell->idle_workers);
}

/* Task runner callback object. */
/* It is invoked by QTEE to run a task in QTEE. */

static int op_callrunnable(struct si_arg args[])
{
	struct si_object_invoke_ctx *oic;
	struct si_arg null_args[1] = { 0 };
	int ret, result = 0;

	/* IRunnable_OP_run expect single runnable object. */
	if (size_of_arg(args) != 1 || args[0].type != SI_AT_IO)
		return -EINVAL;

	oic = kzalloc(sizeof(*oic), GFP_KERNEL);
	if (!oic)
		return -ENOMEM;

retry:
	/* IRunnable_OP_run is 0. */
	ret = si_object_do_invoke(oic, args[0].o, 0, null_args, &result);
	/* TA requested the doorbell could be the target, could be adeadlock. */
	if (!ret && result == OBJECT_ERROR_BUSY)
		goto retry;

	/* Drop the runnable object after invoking it. */
	put_si_object(args[0].o);

	kfree(oic);

	return ret;
}

static void task_runner_cbo_notify(unsigned int context_id,
				   struct si_object *object, int status)
{
	/* NOTHING TO DO HERE. */
}

static void task_runner_cbo_release(struct si_object *object)
{
	/* NOTHING TO DO HERE. */
}

static int task_runner_cbo_dispatch(unsigned int context_id,
				    struct si_object *object, unsigned long op,
				    struct si_arg args[])
{
	int ret;

	switch (SI_OBJECT_OP_METHOD_ID(op)) {
	case SI_OBJECT_OP_CALLRUNNABLE:
		ret = op_callrunnable(args);
		break;
	default:
		ret = -EINVAL;
		break;
	}

	return ret;
}

static struct si_object_operations task_runner_cbo_ops = {
	.notify = task_runner_cbo_notify,
	.release = task_runner_cbo_release,
	.dispatch = task_runner_cbo_dispatch,
};

/* END. Task runner callback object. */

/* Helper to open a service; close using put_si_object(). */
static struct si_object *si_core_service_open(u32 uid)
{
	struct si_object *client_env = NULL_SI_OBJECT;
	struct si_object *object = NULL_SI_OBJECT;
	struct si_object_invoke_ctx *oic;

	oic = kzalloc(sizeof(*oic), GFP_KERNEL);
	if (!oic)
		return NULL_SI_OBJECT;

	if (!si_core_get_client_env(oic, &client_env)) {
		/* Open the service defined using @uid. */
		si_core_client_env_open(oic, client_env, uid, &object);
	}

	put_si_object(client_env);
	kfree(oic);

	return object;
}

/* Doorbell memory object. */

static void doorbell_mo_release(void *private)
{
	struct doorbell_mo_info *mo_info = private;
	/* Get the sgt back from the mem-object. */
	struct sg_table *sgt = mem_object_to_sgt(mo_info->object);

	sg_free_table(sgt);
	kfree(sgt);
	free_pages_exact(mo_info->vaddr, mo_info->size);
}

static int doorbell_mo_info_init(struct doorbell_mo_info *mo_info)
{
	struct sg_table *sgt;
	int ret;

	mo_info->size = DOORBELL_MO_SIZE;
	mo_info->vaddr = alloc_pages_exact(mo_info->size, GFP_KERNEL);
	if (!mo_info->vaddr)
		return -ENOMEM;

	sgt = kzalloc(sizeof(*sgt), GFP_KERNEL);
	if (!sgt) {
		ret = -ENOMEM;
		goto err_free_buf;
	}

	/* Wrap it into a 1-entry sg_table for the mem-object API. */
	ret = sg_alloc_table(sgt, 1, GFP_KERNEL);
	if (ret)
		goto err_free_sgt;

	sg_set_page(sgt->sgl, virt_to_page(mo_info->vaddr), mo_info->size, 0);
	/* Tag and flags are 0 here; adjust if needed. */
	mo_info->object = init_si_mem_object_sg(sgt, 0, 0, doorbell_mo_release,
						mo_info);
	if (mo_info->object == NULL_SI_OBJECT) {
		ret = -EINVAL;
		goto err_free_sgt_table;
	}

	return 0;

err_free_sgt_table:
	sg_free_table(sgt);
err_free_sgt:
	kfree(sgt);
err_free_buf:
	free_pages_exact(mo_info->vaddr, mo_info->size);

	return ret;
}

/* Undo doorbell_init(). */
static void doorbell_deinit(struct doorbell *doorbell)
{
	destroy_workqueue(doorbell->wq);
	put_si_object(doorbell->task_runner);
	put_si_object(doorbell->service);
	/* Drop our copy of mo and cbo. */
	put_si_object(&doorbell->cbo);
	put_si_object(doorbell->mo_info.object);
}

static int doorbell_init(struct doorbell *doorbell)
{
	struct si_object *object;
	int ret;

	spin_lock_init(&doorbell->lock);
	INIT_LIST_HEAD(&doorbell->idle_workers);
	INIT_LIST_HEAD(&doorbell->busy_workers);
	doorbell->pending = false;

	/* Allocate buffer and create a memory object. */
	ret = doorbell_mo_info_init(&doorbell->mo_info);
	if (ret)
		return ret;

	init_si_object_user(&doorbell->cbo, SI_OT_CB_OBJECT,
			    &task_runner_cbo_ops, "task_runner_cbo_obj");

	object = si_core_service_open(SI_DOORBELL_UID);
	if (object == NULL_SI_OBJECT) {
		ret = -ENODEV;
		goto err_exit;
	}

	doorbell->service = object;
	object = si_core_service_open(SI_REGISTER_TASK_RUNNER_UID);
	if (object == NULL_SI_OBJECT) {
		ret = -ENODEV;
		goto err_exit;
	}

	doorbell->task_runner = object;
	doorbell->wq = alloc_workqueue("qtee_doorbell", WQ_UNBOUND,
				       DOORBELL_CONCURRENT_RUNNER_NR);
	if (!doorbell->wq) {
		ret = -ENOMEM;
		goto err_exit;
	}

	return 0;

err_exit:
	put_si_object(doorbell->task_runner);
	put_si_object(doorbell->service);
	put_si_object(&doorbell->cbo);
	put_si_object(doorbell->mo_info.object);

	return ret;
}

static int task_runner_cbo_register(struct doorbell *doorbell)
{
	struct si_object_invoke_ctx *oic;
	struct si_arg args[3] = { 0 };
	int ret, result;
	u32 flags = 0;

	oic = kzalloc(sizeof(*oic), GFP_KERNEL);
	if (!oic)
		return -ENOMEM;

	/* Sent a copy of cbo to QTEE; keep the ownership. */
	get_si_object(&doorbell->cbo);

	/* Init arguments: */
	args[0].b = (struct si_buffer) { {&flags}, sizeof(flags) };
	args[0].type = SI_AT_IB;
	args[1].o = &doorbell->cbo;
	args[1].type = SI_AT_IO;
	args[2].type = SI_AT_END;

	/* IRegisterTaskRunner_OP_registerRunner is 0. */
	ret = si_object_do_invoke(oic, doorbell->task_runner, 0, args, &result);
	/* If !ret, si_object_do_invoke() handles put_si_object(). */

	kfree(oic);

	return ret;
}

static int doorbell_irq_register(struct doorbell *doorbell, uint32_t irq)
{
	struct si_object_invoke_ctx *oic;
	struct si_arg args[3] = { 0 };
	int ret, result;

	oic = kzalloc(sizeof(*oic), GFP_KERNEL);
	if (!oic)
		return -ENOMEM;

	/* Sent a copy of mo to QTEE; keep the ownership. */
	get_si_object(doorbell->mo_info.object);

	/* Init arguments: */
	args[0].b = (struct si_buffer) { {&irq}, sizeof(irq) };
	args[0].type = SI_AT_IB;
	args[1].o = doorbell->mo_info.object;
	args[1].type = SI_AT_IO;
	args[2].type = SI_AT_END;

	/* IDoorbell_OP_registerInterrupt is 0. */
	ret = si_object_do_invoke(oic, doorbell->service, 0, args, &result);
	/* If !ret, si_object_do_invoke() handles put_si_object(). */

	kfree(oic);

	return ret;
}

/* Doorbell IRQ handling. */

static void ack_doorbell(void)
{
	int ret;

	ret = qcom_scm_invoke_ack_doorbell(0, 0);
	if (ret)
		pr_err("doorbell_ack scm call failed with %d!\n", ret);
}

/**
 * worker_oic_init() - Init worker's $struct si_object_invoke_ctx instance.
 * @worker: worker that owns the $struct si_object_invoke_ctx instance.
 * @msg: doorbell message providing the source buffer and length.
 *
 * Allocate a new buffer and copy @msg->buff (of size @msg->len) into it,
 * then replace @worker->oic.out.msg.addr with the newly allocated copy.
 *
 * This is intended to snapshot the doorbell payload so it can be processed
 * after the interrupt/doorbell is ACKed. If a previous request exists, it
 * is freed and replaced. The previous pointer may not be NULL when handling a
 * pending IRQ path (e.g. if initialization is retriggered while another
 * doorbell is pending), see task_runner_irq_do_work().
 *
 * Return: 0 on success, -ENOMEM if allocation fails.
 */
static int worker_oic_init(struct runner_worker *worker,
			   const struct doorbell_msg *msg)
{
	void *new_req;

	size_t max = worker->doorbell->mo_info.size -
		offsetof(struct doorbell_msg, buff);

	/* Check if doorbell msg is not corrupted. */
	if (msg->len == 0 || msg->len > max)
		return -EMSGSIZE;

	new_req = kmemdup(msg->buff, msg->len, GFP_KERNEL);
	if (!new_req)
		return -ENOMEM;
	/* !worker->oic.out.msg.addr if it is called for pending irq. */
	kfree(worker->oic.out.msg.addr);
	worker->oic.out.msg.addr = new_req;
	return 0;
}

/**
 * task_runner_irq_do_work() - Workqueue handler for doorbell/IRQ processing.
 * @work: work item embedded in struct runner_worker
 *
 * This function is scheduled from the doorbell/IRQ path. For each doorbell
 * event, it snapshots the shared message payload into @worker storage, ACKs
 * the doorbell immediately to allow QTEE to signal again, and then processes
 * the copied request.
 *
 * The handler also drains any coalesced doorbell events. If another IRQ
 * arrives while work is running, the IRQ path sets @db->pending under
 * @db->lock. After each iteration, this handler checks @db->pending and
 * repeats until no further events are pending. When the queue is drained,
 * it releases the worker via doorbell_worker_free().
 */
static void task_runner_irq_do_work(struct work_struct *work)
{
	struct runner_worker *worker = container_of(work, struct runner_worker,
						    work);
	struct doorbell *db = worker->doorbell;
	unsigned long flags;
	bool pending;
	int ret;

	for (;;) {
		ret = worker_oic_init(worker, db->mo_info.vaddr);
		/* Ack. Continue process this msg. */
		ack_doorbell();

		/*
		 * While processing this msg, single new IRQ could be triggered.
		 * That would schedule new worker if available or set the
		 * pending bit. While this bit is set, no new IRQ could be
		 * triggered.
		 */

		if (ret) {
			pr_err("worker_oic_init failed (ret = %d).\n", ret);
		} else {
			struct qtee_callback *msg = (struct qtee_callback *)
				worker->oic.out.msg.addr;
			/* Process callback request: */
			si_object_invoke(&worker->oic, msg);

			if (worker->oic.errno) {
				pr_err("doorbell_cb failed (errno = %d).\n",
				       worker->oic.errno);
			}
		}

		/*
		 * The first worker finished the processing of the msg, tries
		 * to process the pending bit; otherwise return the worker so
		 * the IRQ handler could reschedule it.
		 */

		spin_lock_irqsave(&db->lock, flags);
		pending = db->pending;
		if (!pending)
			doorbell_worker_free(worker);
		/* Always, picked pending irq. */
		db->pending = false;
		spin_unlock_irqrestore(&db->lock, flags);

		/*
		 * worker has been returned to idle_workers.
		 * A new IRQ could schedule this work before returning,
		 * avoid dropping the IRQs.
		 */

		if (!pending)
			break;
	}
}

/* IRQ HANDLER. */

static irqreturn_t doorbell_irq_handler(int irq, void *data)
{
	struct doorbell *doorbell = data;
	struct runner_worker *worker;
	unsigned long flags;

	spin_lock_irqsave(&doorbell->lock, flags);
	worker = doorbell_worker_alloc(doorbell);
	if (!worker)
		doorbell->pending = true;
	spin_unlock_irqrestore(&doorbell->lock, flags);

	if (worker)
		queue_work(doorbell->wq, &worker->work);

	/* QTEE does not generate new irq unless ack_doorbell(). */

	return IRQ_HANDLED;
}

/* END IRQ HANDLER. */

static struct doorbell *doorbell;

/**
 * si_core_doorbell_init() - Initialize the QTEE doorbell driver instance.
 * @pdev: Platform device providing the doorbell IRQ.
 *
 * This allocates and initializes the main %struct doorbell state, sets up the
 * shared memory object used to receive doorbell messages from QTEE, opens the
 * required QTEE services (doorbell and task-runner), and creates a workqueue
 * used to run doorbell callbacks in process context.
 *
 * A small pool of %struct runner_worker objects is initialized and linked into
 * @doorbell->idle_workers before the IRQ handler is registered. The IRQ handler
 * reserves an idle worker (moving it to @doorbell->busy_workers) and queues its
 * work item to process the doorbell message. If no workers are available, the
 * event is coalesced via @doorbell->pending and drained by the work handler.
 *
 * The hardware IRQ is requested via devm_request_irq(), then the hardware IRQ
 * number (hwirq) is extracted and registered with QTEE via doorbell_irq_register().
 * Finally, the task-runner callback object is registered with QTEE via
 * task_runner_cbo_register().
 *
 * Return: 0 on success, negative errno on failure.
 */
int si_core_doorbell_init(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct runner_worker *worker;
	struct irq_data *irqd;
	unsigned int hwirq;
	int ret, i;

	doorbell = kzalloc(sizeof(*doorbell), GFP_KERNEL);
	if (!doorbell)
		return -ENOMEM;

	doorbell->irq = platform_get_irq_optional(pdev, 0);
	if (doorbell->irq < 0) {
		ret = doorbell->irq;
		goto err_free_doorbell;
	}

	ret = doorbell_init(doorbell);
	if (ret)
		goto err_free_doorbell;

	/* Init workers before registering the handler. */
	for (i = 0; i < DOORBELL_CONCURRENT_RUNNER_NR; i++) {
		worker = &doorbell->workers[i];

		INIT_WORK(&worker->work, task_runner_irq_do_work);
		INIT_LIST_HEAD(&worker->node);
		worker->doorbell = doorbell;
		/* @doorbell->idle_workers init in doorbell_init(). */
		list_add(&worker->node, &doorbell->idle_workers);
	}

	ret = devm_request_irq(dev, doorbell->irq, doorbell_irq_handler, 0,
			       dev_name(dev), doorbell);
	if (ret)
		goto err_doorbell_deinit;

	irqd = irq_get_irq_data(doorbell->irq);
	if (!irqd) {
		ret = -EINVAL;
		goto err_free_irq;
	}
	hwirq = irqd_to_hwirq(irqd);

	/* Let QTEE knows the hwirq that it should trigger. */
	ret = doorbell_irq_register(doorbell, hwirq);
	if (ret)
		goto err_free_irq;

	ret = task_runner_cbo_register(doorbell);
	if (ret)
		goto err_free_irq;

	return 0;

err_free_irq:
	devm_free_irq(dev, doorbell->irq, doorbell);
err_doorbell_deinit:
	doorbell_deinit(doorbell);
err_free_doorbell:
	kfree(doorbell);

	doorbell = NULL;

	return ret;
}

void si_core_doorbell_deinit(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	int irq;

	if (!doorbell)
		return;

	irq = doorbell->irq;
	/* Stop new IRQs first so the handler can't queue more work. */
	disable_irq(irq);
	synchronize_irq(irq);
	devm_free_irq(dev, irq, doorbell);

	/* Make sure any already-queued work has finished. */
	flush_workqueue(doorbell->wq);

	/* Release: */
	doorbell_deinit(doorbell);
	kfree(doorbell);
	/* Done. */
	doorbell = NULL;
}
