# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_MSM_HAB) += msm_hab.o
msm_hab-objs += hab.o hab_linux.o hab_mem_linux.o hab_mimex.o hab_msg.o hab_open.o hab_parser.o hab_pchan.o hab_pipe.o hab_qvm.o hab_qvm_linux.o hab_stat.o hab_vchan.o khab.o khab_test.o qvm_comm.o qvm_comm_linux.o hab_virtio.o hab_virq.o hab_virq_hgy.o hab_virq_qvm.o

