# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_MHI_SATELLITE) += mhi_dev_satellite.o
mhi_dev_satellite-objs += mhi_satellite.o

obj-$(CONFIG_MHI_UCI) += mhi_dev_uci.o
mhi_dev_uci-objs += mhi_uci.o

